### ISSUE TITLE
Sender and Receiver demo does not work across tabs in IE11

### ISSUE THREAD

**Issue by monobyte** [ozone-development/ozp-iwc-angular#8]
The receiver doesn't work across browser tabs in IE11. It does work if both sender and receiver are in the same tab.

**Comment by Kevin-K** [comment]
[IWC #301](https://github.com/ozone-development/ozp-iwc/issues/301) It's come up that in IE11 Iframe local storage events (the transport protocol for IWC) do not trigger storage events unless both clients are on same tab: [MSDN Issue](https://connect.microsoft.com/IE/feedback/details/811546/ie11-localstorage-events-fire-twice-or-not-at-all-in-iframes)

Until further transport protocols are introduced to the IWC IE11 will only be supported within a single page (IWC can function fully within an instance of [ozp-webtop](https://ozone-development/ozp-webtop).
